from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import re
import os

def extract_text_from_pptx(file_path: str) -> str:
    from pptx import Presentation
    prs = Presentation(file_path)
    text = []
    for slide in prs.slides:
        for shape in slide.shapes:
            if hasattr(shape, "text"):
                text.append(shape.text)
    return "\n".join(text)

def extract_text_from_docx(file_path: str) -> str:
    doc = Document(file_path)
    text = [p.text for p in doc.paragraphs if p.text.strip()]
    return "\n".join(text)

def add_formatted_text(paragraph, text):
    """Helper to add text with **bold** and `code` parsed properly to a paragraph."""
    parts = re.split(r'(\*\*.*?\*\*)', text)
    for part in parts:
        if part.startswith("**") and part.endswith("**"):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        else:
            # Also handle inline code `code`
            sub_parts = re.split(r'(`.*?`)', part)
            for sub in sub_parts:
                if sub.startswith("`") and sub.endswith("`"):
                    run = paragraph.add_run(sub[1:-1])
                    run.font.name = 'Courier New'
                    run.font.color.rgb = RGBColor(199, 37, 78) # Dark red for inline code
                else:
                    paragraph.add_run(sub)

def create_docx_from_markdown(markdown_content: str, output_path: str):
    """Parses markdown generated by Gemini and creates a well-formatted Word Document."""
    doc = Document()
    
    # Set default styles
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Arial'
    font.size = Pt(11)

    # Document title
    title = doc.add_heading("Video Insight Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.style.font.color.rgb = RGBColor(0, 51, 102)
    
    in_code_block = False
    
    # Process line by line
    for line in markdown_content.split("\n"):
        line = line.strip()
        
        # Handle code blocks toggling
        if line.startswith("```"):
            in_code_block = not in_code_block
            if in_code_block:
                # Add an empty line before code block
                doc.add_paragraph()
            continue
            
        if in_code_block:
            # Code block styling
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Inches(0.5)
            p.paragraph_format.space_after = Pt(2) # tighter spacing inside code
            run = p.add_run(line)
            run.font.name = 'Courier New'
            run.font.size = Pt(9.5)
            run.font.color.rgb = RGBColor(40, 44, 52) # Dark greyish
            continue

        if not line:
            continue
            
        if line.startswith("# "):
            heading = doc.add_heading(line[2:].strip(), level=1)
            heading.style.font.color.rgb = RGBColor(0, 51, 102) # Dark blue
            heading.paragraph_format.space_before = Pt(24)
            heading.paragraph_format.space_after = Pt(12)
        elif line.startswith("## "):
            heading = doc.add_heading(line[3:].strip(), level=2)
            heading.style.font.color.rgb = RGBColor(0, 102, 204)
            heading.paragraph_format.space_before = Pt(18)
            heading.paragraph_format.space_after = Pt(6)
        elif line.startswith("### "):
            heading = doc.add_heading(line[4:].strip(), level=3)
            heading.style.font.color.rgb = RGBColor(0, 102, 153)
            heading.paragraph_format.space_before = Pt(12)
            heading.paragraph_format.space_after = Pt(6)
        elif line.startswith("- ") or line.startswith("* "):
            text = line[2:].strip()
            p = doc.add_paragraph(style='List Bullet')
            p.paragraph_format.space_after = Pt(4)
            add_formatted_text(p, text)
        else:
            p = doc.add_paragraph()
            p.paragraph_format.space_after = Pt(8)
            add_formatted_text(p, line)
                    
    doc.save(output_path)
    return output_path
